# @package _global_

run_name: "glm_tts_ots_on_vctk_text_robust"
device: "cuda:0"
base_dir: "."

vc:
  mode: "ots"
  model: "glm_tts"

output_paths:
  metrics_file: "results/glm_tts_ots_on_vctk_text_robust/metrics.json"

adversary:
  code_path: "checkpoints/GLM-TTS"
  ckpt_dir: "/tealab-data/rjin02/GLM-TTS-ckpt"
  frontend_dir: "/tealab-data/rjin02/AudioWatermarkBench/checkpoints/GLM-TTS/frontend"
  sample_rate: 24000
  use_cache: true
  use_phoneme: false
  sample_method: "ras"
  seed: null
  max_samples: null
  default_prompt_text: "Here is a sample of the desired voice."

batch_size: 16 # not used in VC

defaults:
  - _self_
  - /dataset: vctk_text_robust

evaluation:
  bootstrap:
    enabled: true
    num_samples: 1000
    confidence_level: 0.95
    seed: null
