# @package _global_
run_name: "bert_ots_on_libritts_with_denoiser_dns64_on_spec"
device: "cuda:0"
base_dir: "."
protected_audio_dir: "/tealab-data/rjin02/AudioWatermarkBench/results/denoiser_dns64_on_spec_libritts/20260104-071333/denoised_audio/protected_audio"

vc:
  mode: "ots"
  model: "bertvits2"

evaluation:
  bootstrap:
    enabled: true
    num_samples: 1000
    confidence_level: 0.95
    seed: null

output_paths:
  metrics_file: "results/bert_ots_on_libritts_with_denoiser_dns64_on_spec/metrics.json"

batch_size: 16 # not used in VC

defaults:
  - _self_
  - /dataset: libritts
  - /adversary: bertvits2_ots
