# @package _global_

run_name: moss_ttsd_ots_on_libritts_with_spec
device: cuda:0
base_dir: .
protected_audio_dir: /tealab-data/rjin02/AudioWatermarkBench/results/spec_on_libritts/20251201-141229/protected_audio
vc:
  mode: ots
  model: moss_ttsd
output_paths:
  metrics_file: results/moss_ttsd_ots_on_libritts_with_spec/metrics.json
batch_size: 16 # not used in VC
adversary:
  code_path: checkpoints/MOSS-TTSD
  model_path: checkpoints/MOSS-TTSD/model
  spt_config_path: checkpoints/MOSS-TTSD/XY_Tokenizer/config/MOSS_TTSD_tokenizer.yaml
  spt_checkpoint_path: checkpoints/MOSS-TTSD/XY_Tokenizer/weights/MOSS_TTSD_tokenizer
  system_prompt: You are a speech synthesizer that generates natural, realistic, and human-like audio from text.
  torch_dtype: bf16
  attn_implementation: sdpa
  use_normalize: true
  silence_duration: 0.0
  reference_assignment: round_robin
  max_samples: null
  seed: null
  default_prompt_text: Here is a short sample of the desired voice.
  use_prompt_transcript: false
defaults:
  - _self_
  - /dataset: libritts
evaluation:
  bootstrap:
    enabled: true
    num_samples: 1000
    confidence_level: 0.95
    seed: null
