# @package _global_

run_name: fishspeech_ots_on_libritts_with_gaussian_noise
device: cuda:0
base_dir: .
protected_audio_dir: /tealab-data/rjin02/AudioWatermarkBench/results/grnoise_on_libritts/20251130-144554/protected_audio
vc:
  mode: ots
  model: fishspeech
output_paths:
  metrics_file: results/fishspeech_ots_on_libritts_with_gaussian_noise/metrics.json
adversary:
  name: fishspeech_ots
  code_path: checkpoints/fish_speech
  llama_checkpoint_path: checkpoints/fish_speech/openaudio-s1-mini
  decoder_checkpoint_path: checkpoints/fish_speech/openaudio-s1-mini/codec.pth
  decoder_config_name: modded_dac_vq
  mode: tts
  half: false
  compile: false
  max_new_tokens: 1024
  chunk_length: 200
  top_p: 0.8
  repetition_penalty: 1.1
  temperature: 0.8
  normalize: true
  use_memory_cache: 'off'
  format: wav
  reference_assignment: round_robin
  default_reference_text: Here is a sample exhibiting the desired voice characteristics.
  seed: null
  max_samples: null
batch_size: 16 # not used in VC
defaults:
  - _self_
  - /dataset: libritts
evaluation:
  bootstrap:
    enabled: true
    num_samples: 1000
    confidence_level: 0.95
    seed: null
