# Dataset Configuration for Bilingual UEDIN

name: "Bilingual_UEDIN"
root_path: "./data/Bilingual_uedin"
# Set to null to include all speakers discovered under audios/
speaker_id: null
max_wav_value: 32768.0

sampling_rate: 96000


filter_length: 8192
hop_length: 2048
win_length: 8192

n_mel_channels: 128
mel_fmin: 0.0

mel_fmax: 48000.0

add_blank: true


n_speakers: 30

cleaned_text: false

return_path: true
