# Dataset Configuration for IEMOCAP

name: "IEMOCAP"
root_path: "./data/audiobenchmarkdataset/iemocap"
# Set to null to include all speakers discovered under audios/
speaker_id: null
max_wav_value: 32768.0

sampling_rate: 16000

filter_length: 1024
hop_length: 256
win_length: 1024

n_mel_channels: 80
mel_fmin: 0.0

mel_fmax: 8000.0

add_blank: true

n_speakers: 30

cleaned_text: false

return_path: true
