# Dataset Configuration

name: "LibriTTS"
root_path: "./data/Libritts" # /data/rjin02/project/AudioWatermarkBench/results/safespeech_on_vctk/20251008-151202/protected_audio
speaker_id: null #  null for all speaker
max_wav_value: 32768.0
sampling_rate: 24000
filter_length: 2048
hop_length: 512
win_length: 2048
n_mel_channels: 128
mel_fmin: 0.0
mel_fmax: null
add_blank: true
n_speakers: 850
cleaned_text: true
# voice cloning defaults
return_path: true
