# Dataset Configuration for Multispeaker LibriSpeech

name: "Multispeaker_libri"
root_path: "./data/Multispeaker_libri"
# Set to null to include all speakers discovered under audios/
speaker_id: null  # Will use all 10 speakers: 61, 237, 908, 1221, 1284, 2300, 2830, 4970, 6829, 7729
max_wav_value: 32768.0
sampling_rate: 16000  # LibriSpeech is 16kHz
filter_length: 2048
hop_length: 512
win_length: 2048
n_mel_channels: 128
mel_fmin: 0.0
mel_fmax: null
add_blank: true
n_speakers: 10  # 10 target speakers
cleaned_text: true
return_path: true
