# Dataset Configuration

name: "VCTK"
root_path: "./data/VCTK"
speaker_id: null # Default speaker from VCTK dataset "p225" p241
max_wav_value: 32768.0
sampling_rate: 48000
filter_length: 2048
hop_length: 512
win_length: 2048
n_mel_channels: 128
mel_fmin: 0.0
mel_fmax: null
add_blank: true
n_speakers: 40
cleaned_text: true
return_path: true
