# @package _global_

defaults:
  - _self_
  - override /dataset: dummy
  - override /model: default
  - override /protection: default

base_dir: .
run_name: dummy_on_dummy
device: cpu

protection:
  name: Dummy
  sampling_rate: 16000

output_paths:
  metrics_file: "metrics.json"
