# @package _global_

run_name: kimi_audio_ots_on_libritts_with_pop
device: cuda:0
base_dir: .
protected_audio_dir: /tealab-data/rjin02/AudioWatermarkBench/results/em_on_libritts/20251216-124950/protected_audio
vc:
  mode: ots
  model: kimi_audio
output_paths:
  metrics_file: results/kimi_audio_ots_on_libritts_with_pop/metrics.json
adversary:
  code_path: checkpoints/Kimi-Audio
  model_path: moonshotai/Kimi-Audio-7B-Instruct
  load_detokenizer: true
  audio_temperature: 0.9
  audio_top_k: 10
  text_temperature: 0.0
  text_top_k: 5
  audio_repetition_penalty: 1.0
  audio_repetition_window_size: 64
  text_repetition_penalty: 1.0
  text_repetition_window_size: 16
  max_new_tokens: -1
  reference_assignment: round_robin
  instruction_template: 'Read the following text using the voice in above example. Text: {text}'
  max_samples: null
  seed: null
batch_size: 16 # not used in VC
defaults:
  - _self_
  - /dataset: libritts
evaluation:
  bootstrap:
    enabled: true
    num_samples: 1000
    confidence_level: 0.95
    seed: null
