# @package _global_

run_name: vall_e_ots_on_libritts_with_pop
device: cuda:0
base_dir: .
protected_audio_dir: /tealab-data/rjin02/AudioWatermarkBench/results/em_on_libritts/20251216-124950/protected_audio
vc:
  mode: ots
  model: vall_e
output_paths:
  metrics_file: results/vall_e_ots_on_libritts_with_pop/metrics.json
adversary:
  code_path: checkpoints/vall-e
  checkpoint_path: checkpoints/vall-e/examples/libritts/exp/valle/best-valid-loss.pt
  text_extractor: espeak
  top_k: -100
  temperature: 1.0
  output_sample_rate: 24000
  reference_assignment: round_robin
  max_samples: null
  default_prompt_text: Here is a sample of the desired voice.
batch_size: 16 # not used in VC
defaults:
  - _self_
  - /dataset: libritts
evaluation:
  bootstrap:
    enabled: true
    num_samples: 1000
    confidence_level: 0.95
    seed: null
