# @package _global_
run_name: "cosy_ots_eval_only_vctk"
device: "cuda:0"
base_dir: "."

vc:
  mode: "ots"
  evaluate_only: true
  evaluation:
    generated_audio_dir: "/tealab-data/rjin02/AudioWatermarkBench/results/cosyvoice_ots_on_vctk/20251122-145159/generated_audio"
    max_samples: null

output_paths:
  metrics_file: "results/cosyvoice_ots_on_vctk/metrics.json"

batch_size: 16

defaults:
  - _self_
  - /dataset: vctk
evaluation:
  bootstrap:
    enabled: true
    num_samples: 1000
    confidence_level: 0.95
    seed: null
